/**
 * Generated by diagnostics.test.ts (WRITE_DIAG=1) from the front end's source: the codes and message templates
 * of every diagnostic it can emit. `‹…›` marks a part that depends on the program. Do not edit.
 */
export const EMITTED: { code: string; severity: 'error' | 'warning'; messages: string[] }[] = [
  {
    "code": "bad-assignment",
    "severity": "error",
    "messages": [
      "cannot assign to `‹name›`: it is ‹what›",
      "unknown output `‹name›`",
      "`‹name›` is an output of `‹name›`",
      "`‹name›` has no input `‹name›`",
      "a test can assign an input of a simulated instance (`c.port = …`) or a test variable"
    ]
  },
  {
    "code": "bad-call",
    "severity": "error",
    "messages": [
      "`write` takes 3 arguments: address, data and enable",
      "`‹name›` takes ‹n› argument(s)",
      "memories have `read` and `write`, not `‹method›`",
      "`read` takes one argument: the address",
      "unknown method `‹method›`",
      "`‹name›` is a module, not a function",
      "`concat` needs at least one argument",
      "the repeat count must be at least 1",
      "`clog2` needs a positive argument",
      "`random` can only be used in tests",
      "`random` takes a type, as in `random(bits<8>)`",
      "cannot generate a random ‹type›"
    ]
  },
  {
    "code": "bad-condition",
    "severity": "error",
    "messages": [
      "a condition must be a `bit`"
    ]
  },
  {
    "code": "bad-expression",
    "severity": "error",
    "messages": [
      "strings are allowed only in `print`",
      "an array cannot be empty",
      "a type is not a value",
      "`sim` can only be used in a test, as `let x = sim M(…)`",
      "`‹name›` is ‹what›, not a value",
      "`_` is allowed only as a match pattern",
      "`‹name›` is a memory",
      "`‹name›` is an instance",
      "`‹name›` is a simulated instance",
      "`write` is a statement, not a value"
    ]
  },
  {
    "code": "bad-field",
    "severity": "error",
    "messages": [
      "`‹value›` has no fields",
      "`‹name›` has no field `‹name›`"
    ]
  },
  {
    "code": "bad-generics",
    "severity": "error",
    "messages": [
      "a `top` module cannot have generic parameters",
      "`‹name›` takes ‹n› generic argument(s)"
    ]
  },
  {
    "code": "bad-next",
    "severity": "error",
    "messages": [
      "`‹name›` is not a register",
      "unknown register `‹name›`",
      "`‹name›` is not an array register"
    ]
  },
  {
    "code": "bad-operand",
    "severity": "error",
    "messages": [
      "`‹op›` needs bits operands",
      "a shift amount cannot be negative",
      "a shift amount must be `bits<M>`",
      "a shift amount must be unsigned",
      "`‹op›` needs `bit` operands",
      "`‹op›` needs a bits operand",
      "only bit vectors can be sliced",
      "shifting a run-time integer needs an integer amount",
      "`‹op›` does not apply to enums",
      "`‹op›` does not apply to ‹arrays or structs›",
      "`‹value›` cannot be indexed",
      "`‹name›` needs a ‹bits or bits<N>› value",
      "`‹name›` converts bit vectors",
      "cannot match on ‹type›"
    ]
  },
  {
    "code": "bad-pattern",
    "severity": "error",
    "messages": [
      "a match pattern must be a constant"
    ]
  },
  {
    "code": "bad-size",
    "severity": "error",
    "messages": [
      "array size must be between 1 and 65536",
      "an array needs at least one element"
    ]
  },
  {
    "code": "bad-slice",
    "severity": "error",
    "messages": [
      "the slice bounds are reversed",
      "slice out of range"
    ]
  },
  {
    "code": "bad-step",
    "severity": "error",
    "messages": [
      "`step` needs a simulated instance"
    ]
  },
  {
    "code": "bad-type",
    "severity": "error",
    "messages": [
      "arrays of `int` are not hardware",
      "`‹name›` takes ‹n› argument(s)",
      "generic parameters must be `int`",
      "a port cannot be an `int`",
      "a `let` is a wire and cannot be an `int`",
      "a memory must have an array type `[T; N]`",
      "only `bits<N>` and `signed<N>` can be used as typed literals"
    ]
  },
  {
    "code": "bad-width",
    "severity": "error",
    "messages": [
      "a width must be between 1 and 65536",
      "`trunc` cannot widen ‹type› to ‹n› bits",
      "`‹name›` cannot narrow ‹type› to ‹n› bits"
    ]
  },
  {
    "code": "bad-write",
    "severity": "error",
    "messages": [
      "`‹name›` is not a memory",
      "unknown memory `‹name›`"
    ]
  },
  {
    "code": "cannot-infer",
    "severity": "error",
    "messages": [
      "cannot infer the type of `‹name›`: its value depends on itself",
      "cannot infer the generic parameter `‹name›` of `‹name›`"
    ]
  },
  {
    "code": "clock-domain",
    "severity": "error",
    "messages": [
      "‹what› is clocked by `‹clock›` but reads a value clocked by ‹list›"
    ]
  },
  {
    "code": "clock-misuse",
    "severity": "error",
    "messages": [
      "a struct field cannot be a clock",
      "arrays of clocks are not allowed",
      "an output cannot be a clock",
      "a constant cannot be a clock",
      "a `let` cannot be a clock",
      "`‹name›` is not a clock input of this module",
      "‹what› `‹name›` needs a clock, but this module has no clock input",
      "this module has several clocks, so ‹what› `‹name›` must say which one clocks it",
      "a simulated instance's clock is driven by `step`",
      "the clock `‹name›` must be connected to a clock input",
      "a function parameter cannot be a clock",
      "a clock cannot be used as data",
      "a clock cannot be read",
      "a clock is driven by `step`"
    ]
  },
  {
    "code": "comb-loop",
    "severity": "error",
    "messages": [
      "combinational loop"
    ]
  },
  {
    "code": "cycle",
    "severity": "error",
    "messages": [
      "the constant `‹name›` depends on itself"
    ]
  },
  {
    "code": "double-assignment",
    "severity": "error",
    "messages": [
      "output `‹name›` is assigned twice"
    ]
  },
  {
    "code": "double-connection",
    "severity": "error",
    "messages": [
      "input `‹name›` is connected twice"
    ]
  },
  {
    "code": "double-next",
    "severity": "error",
    "messages": [
      "register `‹name›` has more than one `next`",
      "element ‹index› of register `‹name›` has more than one `next`"
    ]
  },
  {
    "code": "duplicate",
    "severity": "error",
    "messages": [
      "`‹name›` is declared twice",
      "field `‹name›` is declared twice",
      "variant `‹name›` is declared twice",
      "field `‹name›` is given twice"
    ]
  },
  {
    "code": "empty-type",
    "severity": "error",
    "messages": [
      "struct `‹name›` has no fields",
      "enum `‹name›` has no variants"
    ]
  },
  {
    "code": "index-out-of-range",
    "severity": "error",
    "messages": [
      "index ‹i› is out of range for `‹name›`",
      "index ‹value› is out of range"
    ]
  },
  {
    "code": "index-width",
    "severity": "error",
    "messages": [
      "a dynamic index into ‹n› ‹elements or bits› must have type `bits<‹N›>`"
    ]
  },
  {
    "code": "literal-no-context",
    "severity": "error",
    "messages": [
      "this literal has no type"
    ]
  },
  {
    "code": "literal-too-wide",
    "severity": "error",
    "messages": [
      "literal does not fit `‹type›`"
    ]
  },
  {
    "code": "loop-too-long",
    "severity": "error",
    "messages": [
      "this loop unrolls into more than 65536 copies"
    ]
  },
  {
    "code": "match-incomplete",
    "severity": "error",
    "messages": [
      "this match does not cover every value of ‹value›"
    ]
  },
  {
    "code": "missing-field",
    "severity": "error",
    "messages": [
      "missing field(s) ‹list›"
    ]
  },
  {
    "code": "missing-next",
    "severity": "error",
    "messages": [
      "register `‹name›` has no `next` value"
    ]
  },
  {
    "code": "multiple-top",
    "severity": "error",
    "messages": [
      "only one module can be `top`"
    ]
  },
  {
    "code": "naming",
    "severity": "warning",
    "messages": [
      "‹what› `‹name›` should be ‹style›"
    ]
  },
  {
    "code": "not-constant",
    "severity": "error",
    "messages": [
      "‹what› must be a compile-time integer",
      "‹what› must be a compile-time constant",
      "the value of `‹name›` is not a compile-time constant",
      "the initial value of a register must be a constant",
      "the initial contents of a memory must be constant",
      "expected a compile-time integer"
    ]
  },
  {
    "code": "overlapping-arms",
    "severity": "error",
    "messages": [
      "more than one `_` arm",
      "match arms overlap"
    ]
  },
  {
    "code": "read-output",
    "severity": "error",
    "messages": [
      "cannot read the output `‹name›`"
    ]
  },
  {
    "code": "recursive-fn",
    "severity": "error",
    "messages": [
      "function `‹name›` calls itself"
    ]
  },
  {
    "code": "recursive-module",
    "severity": "error",
    "messages": [
      "module `‹name›` contains itself"
    ]
  },
  {
    "code": "recursive-type",
    "severity": "error",
    "messages": [
      "the type `‹name›` contains itself"
    ]
  },
  {
    "code": "reg-array-coverage",
    "severity": "error",
    "messages": [
      "not every element of register `‹name›` has a `next`"
    ]
  },
  {
    "code": "syntax",
    "severity": "error",
    "messages": [
      "expected `‹text›`‹context›, found ‹token›",
      "expected ‹what›, found ‹token›",
      "expected the end of the statement, found ‹token›",
      "expected an item (`module`, `fn`, `struct`, `enum`, `type`, `const` or `test`), found ‹token›",
      "expected `,` or `)` in the port list, found ‹token›",
      "unknown attribute `@‹name›`",
      "expected the test's name as a string, found ‹token›",
      "a register needs a type",
      "a register needs an initial value",
      "expected `=` after `‹name›`, found ‹token›",
      "expected a statement, found ‹token›",
      "expected a test statement, found ‹token›",
      "comparisons cannot be chained",
      "expected an expression, found the end of the line",
      "expected an expression, found ‹token›",
      "`if` needs an `else`",
      "expected `,` or `}` after the match arm, found ‹token›",
      "unterminated block comment",
      "invalid digit `‹digit›` in ‹kind› literal",
      "number literal with no digits",
      "unterminated string",
      "unexpected character `‹char›`"
    ]
  },
  {
    "code": "too-many-reads",
    "severity": "error",
    "messages": [
      "memory `‹name›` has at most two read ports"
    ]
  },
  {
    "code": "too-many-writes",
    "severity": "error",
    "messages": [
      "memory `‹name›` can have only one write port"
    ]
  },
  {
    "code": "type-mismatch",
    "severity": "error",
    "messages": [
      "type mismatch",
      "expected a compile-time integer",
      "wrong number of elements"
    ]
  },
  {
    "code": "unassigned-output",
    "severity": "error",
    "messages": [
      "output `‹name›` is never assigned"
    ]
  },
  {
    "code": "unconnected-input",
    "severity": "error",
    "messages": [
      "input(s) ‹list› not connected"
    ]
  },
  {
    "code": "unknown-module",
    "severity": "error",
    "messages": [
      "unknown module `‹name›`"
    ]
  },
  {
    "code": "unknown-name",
    "severity": "error",
    "messages": [
      "unknown name `‹name›`",
      "unknown function `‹name›`"
    ]
  },
  {
    "code": "unknown-port",
    "severity": "error",
    "messages": [
      "`‹name›` is an output of `‹name›`, not an input",
      "`‹name›` has no input `‹name›`",
      "`‹name›` is an input of `‹name›`",
      "`‹name›` has no output `‹name›`",
      "`‹name›` has no port `‹name›`"
    ]
  },
  {
    "code": "unknown-type",
    "severity": "error",
    "messages": [
      "unknown type `‹name›`",
      "`‹name›` is not a struct",
      "unknown struct `‹name›`"
    ]
  },
  {
    "code": "unknown-variant",
    "severity": "error",
    "messages": [
      "`‹name›` has no variant `‹name›`"
    ]
  },
  {
    "code": "unreachable-arm",
    "severity": "warning",
    "messages": [
      "the `_` arm is never used"
    ]
  },
  {
    "code": "width-mismatch",
    "severity": "error",
    "messages": [
      "width mismatch"
    ]
  }
];
