/**
 * Regenerates `lineshapeTable.ts`: the radiatively corrected hadronic cross-section of e⁺e⁻ → qq̄ from the course generator
 * (`hep/gen`, γ and Z exchange, first QCD correction, initial-state radiation), on a grid of √s and of the number of light
 * neutrino species N_ν, which enters only through the total width in the Z propagator: Γ_Z(N) = Γ_Z(3) + (N − 3) Γ_νν.
 *
 *     node --experimental-strip-types src/lib/sims/part6/makeLineshapeTable.ts
 *
 * The widgets read the table (and interpolate) because a call of `sigmaISR` takes about ten milliseconds.
 */
import { writeFileSync } from 'node:fs';
import { eeToFermions } from '../../hep/gen/index.ts';
import { GAMMA_Z, zPartialWidth } from '../../hep/sm/index.ts';

export const GRID = { e0: 86, de: 0.25, ne: 41, n0: 1, dn: 0.5, nn: 9 };

export function build(): number[][] {
  const gnu = zPartialWidth(12);
  const rows: number[][] = [];
  for (let k = 0; k < GRID.nn; k++) {
    const N = GRID.n0 + k * GRID.dn;
    const p = eeToFermions({ final: 'hadrons', qcd: true, zWidth: GAMMA_Z + (N - 3) * gnu });
    rows.push(Array.from({ length: GRID.ne }, (_, i) => Number((p.sigmaISR(GRID.e0 + i * GRID.de) / 1000).toPrecision(7))));
  }
  return rows;
}

if (process.argv[1]?.endsWith('makeLineshapeTable.ts')) {
  const rows = build();
  const text = `// Generated by makeLineshapeTable.ts from hep/gen. Do not edit.
// σ(e⁺e⁻ → hadrons) in nb, with initial-state radiation, from √s = ${GRID.e0} GeV in steps of ${GRID.de} GeV (${GRID.ne} columns),
// for N_ν = ${GRID.n0}, ${GRID.n0 + GRID.dn}, … ${GRID.n0 + (GRID.nn - 1) * GRID.dn} (${GRID.nn} rows).
export const TABLE_GRID = ${JSON.stringify(GRID)};
export const TABLE: number[][] = ${JSON.stringify(rows)};
`;
  writeFileSync(new URL('./lineshapeTable.ts', import.meta.url), text);
  console.log('wrote', rows.length, 'rows');
}
