/**
 * Makes `ipSample.ts`: simulated light, charm and bottom jets (pT uniform from 30 to 80 GeV, |η| < 1.5) through the `onion` detector simulation and
 * `hep/reco`. For each jet: the b-tag score of the reference tagger and the lifetime-signed impact-parameter significances (largest first) of the tracks
 * the tagger used. The jets are crude (`synthetic.jetParticles`: one B⁰ or D⁰ with a random fraction of the momentum, the rest light hadrons), so what is
 * realistic is the lifetime and flight of the heavy hadron, not the fragmentation.
 *
 *     node --experimental-strip-types src/lib/sims/part6/makeIpSample.ts [jets per flavour]
 */
import { writeFileSync } from 'node:fs';
import { rng } from '../../hep/random/index.ts';
import { presets, simulate } from '../../hep/detector/index.ts';
import { reconstruct, bTagInfo, synthetic } from '../../hep/reco/index.ts';
import { fromPtEtaPhiM, deltaR } from '../../hep/kinematics/index.ts';

const n = Number(process.argv[2] ?? 250);
const r = rng(24680);
const cfg = presets.onion!;
const out: Record<string, number[][]> = { light: [], c: [], b: [] };
for (const flavour of ['light', 'c', 'b'] as const) {
  for (let i = 0; i < n; i++) {
    const pt = 30 + 50 * r(), eta = (2 * r() - 1) * 1.5, phi = (2 * r() - 1) * Math.PI;
    const list = synthetic.jetParticles(r, flavour, pt, eta, phi);
    const truth = synthetic.truthEventFrom(list, [0, 0, 50 * (r() + r() + r() - 1.5) * 0.8]);
    const det = simulate(truth, cfg, r.fork(`${flavour}${i}`));
    const reco = reconstruct(det, cfg, {}, truth);
    const axis = fromPtEtaPhiM(pt, eta, phi, 5);
    const jets = reco.objects.filter((o) => o.kind === 'jet').sort((a, b) => deltaR(a.p, axis) - deltaR(b.p, axis));
    const jet = jets[0];
    if (!jet || deltaR(jet.p, axis) > 0.4) continue;
    const info = bTagInfo(jet.p, reco.tracks, reco.vertices);
    out[flavour]!.push([Number(info.score.toFixed(4)), ...info.significances.slice(0, 12).map((s) => Number(s.toFixed(1)))]);
  }
}
const text = `// Generated by makeIpSample.ts. Do not edit.
// Simulated light, c and b jets (30–80 GeV, |η| < 1.5) from hep/detector and hep/reco. Each row: the reference b-tag score, then the lifetime-signed
// impact-parameter significances of the tracks the tagger used, largest first.
export const IP_SAMPLE: Record<'light' | 'c' | 'b', number[][]> = ${JSON.stringify(out)};
`;
writeFileSync(new URL('./ipSample.ts', import.meta.url), text);
console.log(Object.entries(out).map(([k, v]) => `${k}: ${v.length}`).join(', '));
