<!--
  The search sandbox: the flagship figure of Chapter 32. A hypothetical heavy Z′ with adjustable mass and coupling, generated by hep/gen, looked for in the dimuon
  spectrum on top of the Drell–Yan background, with the 95 % CL limit set by hep/analysis (CLs). A TOY: leading-order generator, a selection and a smearing instead of the detector
  simulation, only Drell–Yan in the background (see ./zprime.ts for every assumption).

    ::search-sandbox{n="32.1" caption="…"}    Props: `mass` (GeV), `coupling`, `lumi` (fb⁻¹), `seed`, `n`, `caption`, `title`.
-->
<script lang="ts">
  import { onMount, untrack } from 'svelte';
  import Widget from '$lib/components/ui/Widget.svelte';
  import Slider from '$lib/components/ui/Slider.svelte';
  import Toggle from '$lib/components/ui/Toggle.svelte';
  import Button from '$lib/components/ui/Button.svelte';
  import HepHist from '$lib/charts/HepHist.svelte';
  import LinePlot from './LinePlot.svelte';
  import { getBackground, signalTemplate, makeModel, pseudoData, limitAt, clsOf, EDGES, N_BINS, SELECTION, massResolution, SQRT_S, type Background, type LimitPoint } from './zprime';
  import { sig, sci } from './format';

  let {
    mass: mass0 = 3000,
    coupling: g0 = 0.4,
    lumi: lumi0 = 140,
    seed: seed0 = 4,
    n,
    caption,
    title = 'Search sandbox: a hypothetical Z′ (simulated, toy)',
  }: { mass?: number; coupling?: number; lumi?: number; seed?: number; n?: string | number; caption?: string; title?: string } = $props();

  let mass = $state(untrack(() => mass0));
  let g = $state(untrack(() => g0));
  let lumi = $state(untrack(() => lumi0));
  let relUnc = $state(0.1);
  let exists = $state(true);
  let seed = $state(untrack(() => seed0));

  let bkg = $state<Background | null>(null);
  let progress = $state(0);
  onMount(() => {
    void getBackground((f) => (progress = f)).then((b) => (bkg = b));
  });

  const MASSES = [1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500, 5000, 5500, 6000];

  // The model at the chosen mass, the pseudo-data, and the verdict for the chosen point.
  const view = $derived.by(() => {
    if (!bkg) return null;
    const t = signalTemplate(mass);
    const model = makeModel(t, bkg, lumi, relUnc);
    const data = pseudoData(model, exists ? g * g : 0, seed);
    const cls = clsOf(mass, g, bkg, lumi, relUnc, data);
    return { t, model, data, cls };
  });

  // The limit curve: computed after a short pause, one mass at a time, so that dragging a slider stays smooth.
  let curve = $state<LimitPoint[]>([]);
  let computing = $state(false);
  let token = 0;
  $effect(() => {
    const v = view;
    const b = bkg;
    if (!v || !b) return;
    const L = lumi, u = relUnc, data0 = v.data.slice();
    const my = ++token;
    computing = true;
    const timer = setTimeout(async () => {
      const out: LimitPoint[] = [];
      for (const M of MASSES) {
        if (my !== token) return;
        // The same pseudo-data are used at every test mass; the data's bins are fixed by the chosen mass, so build them at the test mass from the same seed.
        const t = signalTemplate(M);
        const model = makeModel(t, b, L, u);
        out.push(limitAt(M, b, L, u, data0.length === model.background.length ? data0 : pseudoData(model, 0, seed)));
        await new Promise<void>((r) => setTimeout(r, 0));
      }
      if (my === token) {
        curve = out;
        computing = false;
      }
    }, 150);
    return () => clearTimeout(timer);
  });

  const binCentre = (i: number) => Math.sqrt(EDGES[i]! * EDGES[i + 1]!);
  const series = $derived.by(() => {
    if (!view) return [];
    const { model, data } = view;
    const sum = model.background.map((b, i) => b + (exists ? g * g : g * g) * model.signal[i]!);
    return [
      { edges: EDGES, counts: model.background, label: 'Drell–Yan background (expected)', color: 'var(--series-8)' },
      { edges: EDGES, counts: sum, label: `background + Z′ (M = ${mass} GeV, g = ${sig(g, 2)})`, color: 'var(--series-5)' },
      { edges: EDGES, counts: data, label: exists ? 'pseudo-data (with the Z′)' : 'pseudo-data (background only)', points: true, errors: true, color: 'var(--series-1)' },
    ];
  });
  const ymax = $derived(view ? Math.max(10, ...view.model.background) * 3 : 100);

  const Mt = MASSES.map((m) => m / 1000);
  const obsLine = $derived(curve.map((p) => p.observed));
  const expLine = $derived(curve.map((p) => p.expected));
  const gTop = 3;
  const limAtMass = $derived.by(() => {
    if (curve.length < 2) return null;
    // interpolate log g linearly in mass
    const f = (key: 'observed' | 'expected') => {
      let k = 0;
      while (k < curve.length - 2 && curve[k + 1]!.mass < mass) k++;
      const a = curve[k]!, b = curve[k + 1]!;
      const t = Math.min(1, Math.max(0, (mass - a.mass) / (b.mass - a.mass)));
      return Math.exp(Math.log(a[key]) + t * (Math.log(b[key]) - Math.log(a[key])));
    };
    return { observed: f('observed'), expected: f('expected') };
  });
  const excluded = $derived(view ? view.cls < 0.05 : false);
  const sigWindow = $derived.by(() => {
    if (!view) return null;
    const res = massResolution(mass);
    let s = 0, b = 0, d = 0;
    for (let i = 0; i < N_BINS; i++) {
      const c = binCentre(i);
      if (Math.abs(c - mass) < 2 * res * mass + 0.05 * mass) {
        s += g * g * view.model.signal[i]!;
        b += view.model.background[i]!;
        d += view.data[i]!;
      }
    }
    return { s, b, d };
  });
</script>

<Widget {title} {n} {caption} kind="Simulation">
  {#snippet controls()}
    <Slider bind:value={mass} min={1000} max={6000} step={100} label="Z′ mass [GeV]" format={(v) => v.toFixed(0)} />
    <Slider bind:value={g} min={0.02} max={2} log label="Coupling g (1 = the Z's strength)" format={(v) => sig(v, 2)} />
    <Slider bind:value={lumi} min={10} max={3000} log label="Integrated luminosity [fb⁻¹]" format={(v) => sig(v, 3)} />
    <Slider bind:value={relUnc} min={0} max={0.3} step={0.01} label="Background uncertainty" format={(v) => `${(v * 100).toFixed(0)} %`} />
    <div class="row ui">
      <Toggle bind:checked={exists} label="The Z′ exists (put it in the data)" />
      <Button onclick={() => (seed = seed + 1)} title="Draw the pseudo-data again (next seed)">Re-roll the data <span class="seed">seed {seed}</span></Button>
    </div>
  {/snippet}

  {#if !bkg}
    <p class="ui status" role="status">Generating the Drell–Yan background with hep/gen… {(progress * 100).toFixed(0)} %</p>
  {:else if view}
    <div class="grid">
      <div class="pane">
        <h5 class="ui">The dimuon mass spectrum, {sig(lumi, 3)} fb⁻¹ at {(SQRT_S / 1000).toFixed(1)} TeV</h5>
        <HepHist
          {series}
          x={{ type: 'log', domain: [500, 7000], label: 'dimuon invariant mass [GeV]', tickValues: [500, 1000, 2000, 4000, 7000] }}
          y={{ type: 'log', domain: [0.1, ymax], label: 'events per bin' }}
          markers={[{ x: mass, label: 'Z′ mass', color: 'var(--series-5)', at: 0.95 }]}
          height={300}
          label="Simulated dimuon mass spectrum: Drell–Yan background, background plus a hypothetical Z′, and pseudo-data"
        />
      </div>
      <div class="pane">
        <h5 class="ui">Which couplings are excluded at 95 % confidence?</h5>
        <LinePlot
          lines={[
            ...(curve.length ? [{ x: Mt, y: obsLine, label: 'observed limit on g', color: 'var(--series-1)', fill: false }] : []),
            ...(curve.length ? [{ x: Mt, y: expLine, label: 'expected limit (no Z′)', color: 'var(--series-8)', dash: '6 3' }] : []),
          ]}
          bands={curve.length ? [{ x: Mt, lo: curve.map((p) => p.m1), hi: curve.map((p) => p.p1), color: 'var(--series-8)', opacity: 0.25, label: 'expected ±1σ' }] : []}
          points={[{ x: mass / 1000, y: g, color: excluded ? 'var(--bad)' : 'var(--ok)' }]}
          x={{ domain: [1, 6], label: 'Z′ mass [TeV]' }}
          y={{ type: 'log', domain: [0.01, gTop], label: 'coupling g (× the Z coupling)', tickValues: [0.01, 0.03, 0.1, 0.3, 1, 3] }}
          height={300}
          label="Excluded region in the plane of Z′ mass and coupling: the region above the observed limit is excluded; the chosen point is marked"
          format={(v) => sig(v, 3)}
        />
        <p class="ui small">Above the solid line the coupling is excluded. The marker is your choice of mass and coupling: {excluded ? 'excluded' : 'not excluded'} (filled red or green; the word carries the meaning).</p>
        {#if computing}<p class="ui small" role="status">Updating the limits…</p>{/if}
      </div>
    </div>

    <div class="readout ui" aria-live="polite">
      <div class="card">
        <span class="k">Near the mass (±2σ and more)</span>
        {#if sigWindow}<strong class="v">{sig(sigWindow.s, 3)} signal, {sig(sigWindow.b, 3)} background</strong><span class="s">{sigWindow.d.toFixed(0)} events seen in that window. Width of the Z′ here: {sig(view.t.width, 3)} GeV, mass resolution {(massResolution(mass) * 100).toFixed(1)} %.</span>{/if}
      </div>
      <div class="card" class:hot={excluded}>
        <span class="k">CLs of "a Z′ of this mass and coupling exists"</span>
        <strong class="v">{sci(view.cls, 2)}: {excluded ? 'excluded at 95 %' : 'not excluded'}</strong>
        <span class="s">Excluded if CLs &lt; 0.05. {#if limAtMass}The limit at this mass is g &lt; {sig(limAtMass.observed, 2)} (expected without a Z′: {sig(limAtMass.expected, 2)}).{/if}</span>
      </div>
      <div class="card">
        <span class="k">The toy, in one line</span>
        <span class="s">Leading-order Z′ (sequential couplings × g) and Drell–Yan from hep/gen; both muons |η| &lt; {SELECTION.etaMax}, pT &gt; {SELECTION.ptMin} GeV, {(SELECTION.muonEfficiency * 100).toFixed(0)} % efficiency each; no other background; no detector simulation. Simulated, not data.</span>
      </div>
    </div>
  {/if}
</Widget>

<style>
  .row {
    display: flex;
    flex-wrap: wrap;
    gap: 0.6rem 1rem;
    align-items: center;
    width: 100%;
  }
  .seed {
    font-family: var(--font-mono);
    font-size: 0.72rem;
    color: var(--mute);
    margin-left: 0.3rem;
  }
  .grid {
    display: grid;
    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);
    gap: 1rem;
  }
  @media (max-width: 860px) {
    .grid {
      grid-template-columns: minmax(0, 1fr);
    }
  }
  .pane {
    min-width: 0;
  }
  h5 {
    margin: 0 0 0.35rem;
    font-size: 0.78rem;
    font-weight: 600;
    color: var(--ink-2);
    text-transform: none;
    letter-spacing: 0;
  }
  .status {
    color: var(--mute);
  }
  .small {
    margin: 0.3rem 0 0;
    font-size: 0.78rem;
    color: var(--mute);
  }
  .readout {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 0.6rem;
    margin-top: 0.8rem;
  }
  @media (max-width: 860px) {
    .readout {
      grid-template-columns: minmax(0, 1fr);
    }
  }
  .card {
    border: 1px solid var(--line);
    border-radius: 8px;
    padding: 0.55rem 0.75rem;
    background: var(--pn);
    display: flex;
    flex-direction: column;
    gap: 0.15rem;
  }
  .card.hot {
    border-color: var(--bad);
  }
  .k {
    font-size: 0.72rem;
    color: var(--mute);
    text-transform: none;
    letter-spacing: 0;
  }
  .v {
    font-family: var(--font-mono);
    font-size: 0.95rem;
    font-weight: 600;
  }
  .s {
    font-size: 0.78rem;
    color: var(--ink-2);
    line-height: 1.4;
  }
</style>
