// Glossary: every <Term k="..."> in the course resolves here, and the
// glossary page lists them all.

export interface GlossEntry {
  term: string;
  def: string;
  see?: string; // chapter slug
}

export const GLOSSARY: Record<string, GlossEntry> = {
  'abi': { term: 'ABI (application binary interface)', def: 'The machine-level contract between separately compiled code: calling convention, data layout and alignment, register roles, stack layout, object file format and system-call interface. Two compilers that agree on the ABI can link each other’s code.', see: 'abi' },
  'activation-record': { term: 'activation record', def: 'Another name for a stack frame: the storage for one invocation of a function (return address, saved registers, locals, spill slots, outgoing arguments).', see: 'frames' },
  'addressing-mode': { term: 'addressing mode', def: 'The ways an instruction can compute a memory address. RISC-V offers base + 12-bit offset; AArch64 adds scaled register offsets and pre/post-index; x86-64 offers base + index×scale + disp32 and RIP-relative.', see: 'isel' },
  'alias-analysis': { term: 'alias analysis', def: 'Deciding whether two memory references may refer to the same location. It limits reordering of loads and stores (scheduling, CSE, LICM).', see: 'scheduling' },
  'anti-dependence': { term: 'anti-dependence (WAR)', def: 'An instruction writes a location that an earlier instruction reads. It is a false dependence caused by reusing a name; renaming (SSA, or hardware register renaming) removes it.', see: 'scheduling' },
  'basic-block': { term: 'basic block', def: 'A maximal straight-line sequence of instructions with one entry (the first instruction) and one exit (the terminator at the end). The nodes of a control-flow graph.', see: 'cfg' },
  'back-edge': { term: 'back edge', def: 'A CFG edge whose target dominates its source. Every back edge defines a natural loop headed by its target.', see: 'cfg' },
  'burs': { term: 'BURS (bottom-up rewrite system)', def: 'Instruction selection by tree-pattern rewriting with costs, solved by dynamic programming bottom-up. Tools like BURG and iburg generate such selectors from grammars.', see: 'isel' },
  'callee-saved': { term: 'callee-saved register', def: 'A register a function must preserve: if it writes it, it saves the old value in its prologue and restores it in its epilogue. Values live across calls prefer these registers.', see: 'abi' },
  'caller-saved': { term: 'caller-saved register', def: 'A register a called function may clobber freely. A caller that needs its value after the call must keep it elsewhere (a callee-saved register or the stack).', see: 'abi' },
  'calling-convention': { term: 'calling convention', def: 'The part of the ABI that says where arguments and return values go (registers, stack), which registers survive calls, who cleans up the stack and how it is aligned.', see: 'abi' },
  'cfa': { term: 'CFA (canonical frame address)', def: 'The value of the stack pointer at the call site in the caller, i.e. just before the call. A stable reference point for describing frame layout (DWARF uses it for unwinding).', see: 'frames' },
  'cfg': { term: 'control-flow graph (CFG)', def: 'A directed graph whose nodes are basic blocks and whose edges are the possible transfers of control between them.', see: 'cfg' },
  'coalescing': { term: 'coalescing', def: 'Merging the live ranges of the source and destination of a copy so that both get the same register and the copy can be deleted. Aggressive coalescing can make a graph uncolourable; conservative tests (Briggs, George) avoid that.', see: 'regalloc' },
  'critical-edge': { term: 'critical edge', def: 'An edge from a block with several successors to a block with several predecessors. Code cannot be placed "on" such an edge without splitting it with a new block.', see: 'ssa-destruction' },
  'critical-path': { term: 'critical path', def: 'The longest latency-weighted path through a dependence graph: a lower bound on the schedule length. List schedulers prioritise instructions on it.', see: 'scheduling' },
  'dataflow-analysis': { term: 'dataflow analysis', def: 'Computing facts at every program point by solving equations over the CFG iteratively until a fixed point, e.g. liveness (backward) or reaching definitions (forward).', see: 'liveness' },
  'dominance-frontier': { term: 'dominance frontier', def: 'DF(x) is the set of blocks where x’s dominance ends: y is in DF(x) if x dominates a predecessor of y but does not strictly dominate y. It is exactly where a definition in x may need a phi.', see: 'dominance' },
  'dominator': { term: 'dominator', def: 'Block a dominates block b if every path from the entry to b passes through a. The immediate dominator is the closest strict dominator; they form the dominator tree.', see: 'dominance' },
  'dominator-tree': { term: 'dominator tree', def: 'The tree in which each block’s parent is its immediate dominator. SSA renaming, CSE and structured control-flow recovery all walk it.', see: 'dominance' },
  'elf': { term: 'ELF', def: 'Executable and Linkable Format: the object, executable and shared-library format of Linux and most Unix systems (and many embedded toolchains). Introduced with System V Release 4 (1989).', see: 'objects' },
  'epilogue': { term: 'epilogue', def: 'Code at the end of a function that restores callee-saved registers, frees the stack frame and returns.', see: 'frames' },
  'frame-pointer': { term: 'frame pointer', def: 'A register (s0/x29/rbp) holding a fixed address within the current frame. It makes frames easy to walk for debuggers and profilers, at the cost of one register.', see: 'frames' },
  'graph-coloring': { term: 'graph colouring', def: 'Assigning one of k colours to each node so that adjacent nodes differ. Register allocation colours the interference graph with k = number of registers. NP-complete in general.', see: 'regalloc' },
  'immediate': { term: 'immediate', def: 'A constant operand encoded inside the instruction itself. Every ISA limits immediate sizes, which is why large constants need multi-instruction sequences.', see: 'legalization' },
  'instruction-selection': { term: 'instruction selection', def: 'Choosing target instructions that implement the IR. Usually done by covering expression trees or DAGs with patterns (tiles) of minimal total cost.', see: 'isel' },
  'interference': { term: 'interference', def: 'Two values interfere if they are live at the same time (more precisely, if one is live where the other is defined). Interfering values need different registers.', see: 'regalloc' },
  'interference-graph': { term: 'interference graph', def: 'The graph whose nodes are live ranges and whose edges connect values that interfere. Physical registers appear as pre-coloured nodes.', see: 'regalloc' },
  'ir': { term: 'intermediate representation (IR)', def: 'The compiler’s internal program representation between source language and machine code. Ours, KIR, is a small SSA-based IR in the style of LLVM IR.', see: 'ir' },
  'isa': { term: 'ISA (instruction set architecture)', def: 'The contract between hardware and software: registers, instructions and their encodings, memory model, privilege levels.', see: 'targets' },
  'latency': { term: 'latency', def: 'The number of cycles from an instruction issuing to its result being usable by a dependent instruction.', see: 'scheduling' },
  'legalization': { term: 'legalization', def: 'Rewriting operations and types the target cannot handle directly into ones it can: promoting small types, expanding unsupported operations, splitting large constants, turning operations into library calls.', see: 'legalization' },
  'linear-scan': { term: 'linear scan', def: 'Register allocation over live intervals in a single sweep of a linear instruction order. Fast (roughly linear time), which is why JIT compilers like it.', see: 'linear-scan' },
  'linker': { term: 'linker', def: 'The tool that combines object files into an executable or library: it lays out sections, resolves symbols and applies relocations.', see: 'linking' },
  'live-interval': { term: 'live interval', def: 'The range(s) of positions in a linearised instruction order where a value is live. Linear-scan allocators work on intervals.', see: 'liveness' },
  'live-range': { term: 'live range', def: 'The set of program points where a value is live.', see: 'liveness' },
  'liveness': { term: 'liveness', def: 'A value is live at a point if some path from that point reaches a use of the value without passing a redefinition. Computed by backward dataflow analysis.', see: 'liveness' },
  'lost-copy-problem': { term: 'lost-copy problem', def: 'A bug in naive SSA destruction: a phi copy placed at the end of a predecessor overwrites a value still needed on another outgoing edge. Fixed by splitting critical edges.', see: 'ssa-destruction' },
  'machine-ir': { term: 'machine IR (MIR)', def: 'A low-level representation using target instructions but still virtual registers and abstract stack slots. Register allocation and frame lowering operate on it.', see: 'isel' },
  'mem2reg': { term: 'mem2reg', def: 'The pass that promotes stack slots (allocas) that are only loaded and stored into SSA values, inserting phis. It is how front ends get SSA "for free".', see: 'ssa' },
  'object-file': { term: 'object file', def: 'The output of compiling one translation unit: machine code and data in sections, a symbol table, and relocations describing the holes the linker must fill.', see: 'objects' },
  'parallel-copy': { term: 'parallel copy', def: 'A set of copies that happen simultaneously, like (a, b) := (b, a). Phis at the top of a block form a parallel copy on each incoming edge; sequentialising it may need a temporary.', see: 'ssa-destruction' },
  'peephole': { term: 'peephole optimisation', def: 'Replacing short windows of adjacent instructions by cheaper equivalents. Coined by McKeeman in 1965.', see: 'peephole' },
  'phi': { term: 'φ-function (phi)', def: 'An SSA pseudo-instruction at a join point that selects a value depending on which predecessor control came from.', see: 'ssa' },
  'pipeline': { term: 'pipeline', def: 'Overlapping the execution stages of successive instructions (fetch, decode, execute, memory, write-back). Dependences between nearby instructions cause stalls unless the hardware forwards results or the compiler schedules around them.', see: 'scheduling' },
  'precolored': { term: 'pre-coloured node', def: 'A node in the interference graph for a physical register, whose colour is fixed. Calling conventions and fixed-register instructions appear as pre-coloured nodes.', see: 'regalloc' },
  'prologue': { term: 'prologue', def: 'Code at the start of a function that allocates its stack frame and saves the return address and callee-saved registers it will use.', see: 'frames' },
  'pseudo-instruction': { term: 'pseudo-instruction', def: 'An assembler mnemonic that is not a real hardware instruction but expands into one or more (e.g. RISC-V li, mv, call, ret).', see: 'encoding' },
  'reaching-definition': { term: 'reaching definition', def: 'A definition d reaches point p if some path from d to p does not redefine the variable. A forward dataflow problem.', see: 'liveness' },
  'register-allocation': { term: 'register allocation', def: 'Mapping the unbounded virtual registers of machine IR onto the finite physical register file, inserting spill code where necessary.', see: 'regalloc' },
  'register-pressure': { term: 'register pressure', def: 'The number of values live at a point. When it exceeds the number of registers, something must be spilled.', see: 'spilling' },
  'relaxation': { term: 'relaxation', def: 'Choosing the shortest encoding of instructions whose size depends on addresses (branches, calls), iterating because shrinking one may let another shrink. RISC-V linkers also relax across object files.', see: 'encoding' },
  'relocation': { term: 'relocation', def: 'An instruction to the linker: "at this offset, patch in the address of symbol S (plus A) computed this way". The object file records one wherever the final address is unknown.', see: 'objects' },
  'rematerialization': { term: 'rematerialisation', def: 'Recomputing a value (e.g. a constant) instead of spilling and reloading it. Cheaper than a memory round trip whenever the computation is simple.', see: 'spilling' },
  'reverse-postorder': { term: 'reverse postorder (RPO)', def: 'The reverse of the order in which a depth-first search finishes nodes. In an acyclic graph it is a topological order; forward dataflow analyses converge fastest in RPO.', see: 'cfg' },
  'rip-relative': { term: 'RIP-relative addressing', def: 'x86-64 addressing relative to the address of the next instruction: [rip + disp32]. It makes code position-independent without a global pointer register.', see: 'objects' },
  'scheduling': { term: 'instruction scheduling', def: 'Reordering instructions, while respecting dependences, to reduce stalls and use functional units in parallel.', see: 'scheduling' },
  'section': { term: 'section', def: 'A named, contiguous region of an object file with uniform attributes: .text (code), .data (initialised writable data), .bss (zero-initialised data), .rodata and so on.', see: 'objects' },
  'spill': { term: 'spill', def: 'Keeping a value in memory (a stack slot) instead of a register, adding a store after its definition and loads before its uses.', see: 'spilling' },
  'ssa': { term: 'SSA (static single assignment)', def: 'An IR property: every variable is assigned exactly once, and every use is dominated by its definition. Phis merge values at join points.', see: 'ssa' },
  'ssa-destruction': { term: 'SSA destruction', def: 'Translating out of SSA form by replacing phis with copies on incoming edges, done before or during register allocation.', see: 'ssa-destruction' },
  'stack-machine': { term: 'stack machine', def: 'An execution model where instructions take operands from and push results onto an operand stack, instead of naming registers. WebAssembly and the JVM are stack machines.', see: 'wasm' },
  'swap-problem': { term: 'swap problem', def: 'A bug in naive SSA destruction: phis that permute values, like a₂ = φ(b₁), b₂ = φ(a₁), cannot be replaced by sequential copies without a temporary.', see: 'ssa-destruction' },
  'symbol': { term: 'symbol', def: 'A named address (function, global variable, label) recorded in an object file’s symbol table, either defined in that file or undefined (to be resolved by the linker).', see: 'objects' },
  'tile': { term: 'tile', def: 'A pattern covering one or more IR operations that a single target instruction (or short sequence) implements. Instruction selection covers the IR with tiles.', see: 'isel' },
  'two-address': { term: 'two-address instruction', def: 'An instruction whose destination must also be its first source (x86 add a, b means a += b). The compiler inserts a copy first; coalescing often removes it.', see: 'isel' },
  'virtual-register': { term: 'virtual register', def: 'A register name in machine IR with no limit on how many exist. Register allocation maps each to a physical register or a spill slot.', see: 'isel' },
};
