/**
 * The table of diagnostics in Appendix F: every code the front end can emit is in it, every message the
 * source can produce is in the generated data, and every example provokes its code.
 *
 * Run with WRITE_DIAG=1 to regenerate widgets/diagnostics.gen.ts from the compiler's source.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { check, runTests } from '$lib/hdl';
import { extract, limits } from './extract';
import { ALL_CODES, DIAGNOSTICS, STAGES } from './widgets/diagnostics';
import { EMITTED } from './widgets/diagnostics.gen';

const genPath = new URL('./widgets/diagnostics.gen.ts', import.meta.url);

const render = (found: ReturnType<typeof extract>): string =>
  `/**\n * Generated by diagnostics.test.ts (WRITE_DIAG=1) from the front end's source: the codes and message templates\n * of every diagnostic it can emit. \`‹…›\` marks a part that depends on the program. Do not edit.\n */\nexport const EMITTED: { code: string; severity: 'error' | 'warning'; messages: string[] }[] = ${JSON.stringify(
    found.map(({ code, severity, messages }) => ({ code, severity, messages })),
    null,
    2,
  )};\n`;

if (process.env.WRITE_DIAG) writeFileSync(genPath, render(extract()));

describe('the diagnostics table', () => {
  it('has the compiler’s limits the messages quote', () => {
    expect(limits()).toEqual({ maxWidth: 65536, maxUnroll: 65536 });
  });

  it('matches what the compiler’s source can emit (run with WRITE_DIAG=1 after changing a message)', () => {
    const fresh = extract().map(({ code, severity, messages }) => ({ code, severity, messages }));
    expect(EMITTED).toEqual(fresh);
    expect(readFileSync(genPath, 'utf8')).toBe(render(extract()));
  });

  it('documents every code, once, in a known stage', () => {
    const codes = DIAGNOSTICS.map((d) => d.code);
    expect(new Set(codes).size).toBe(codes.length);
    expect(codes.filter((c) => !ALL_CODES.includes(c))).toEqual([]);
    expect(ALL_CODES.filter((c) => !codes.includes(c))).toEqual([]);
    for (const d of DIAGNOSTICS) expect(STAGES).toContain(d.stage);
  });

  for (const d of DIAGNOSTICS) {
    it(`${d.code}: the example provokes it`, () => {
      const file = `${d.code}.dcl`;
      if (d.test) {
        const r = runTests(d.example, { file });
        const codes = [...r.diagnostics.map((x) => x.code), ...r.results.flatMap((t) => [...(t.error ? ['test-error'] : []), ...t.failures.map(() => 'expect-failed')])];
        expect(codes).toContain(d.code);
      } else {
        const { diagnostics } = check(d.example, { file });
        expect(diagnostics.map((x) => x.code)).toContain(d.code);
        // Only the one under discussion (a warning or two of style are fine).
        const other = diagnostics.filter((x) => x.severity === 'error' && x.code !== d.code && !(d.also ?? []).includes(x.code)).map((x) => `${x.code}: ${x.message}`);
        expect(other).toEqual([]);
      }
    });
  }
});
