// Search over the book: section titles, numbered blocks (definitions, theorems, …) and the
// terms that definitions introduce. The index is generated by the converter (search.json) and
// loaded on first use.

import { useEffect, useId, useMemo, useRef, useState } from 'react';
import type { SearchEntry } from '../content/schema';
import { sourceIndex } from '../content/source';
import { PLANS } from '../content/course';

interface Hit {
  href: string;
  kind: string;
  head: string;
  sub?: string;
  where: string;
  score: number;
}

const KIND: Record<string, string> = {
  section: 'Section', term: 'Term', defn: 'Definition', thm: 'Theorem', lem: 'Lemma', prop: 'Proposition', cor: 'Corollary', ex: 'Example', prob: 'Problem',
};

const fold = (s: string) =>
  s
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase();

function score(words: string[], head: string, rest: string): number {
  const h = fold(head);
  const r = fold(rest);
  let total = 0;
  for (const w of words) {
    if (h.startsWith(w)) total += 6;
    else if (new RegExp(`(^|[^a-z0-9])${w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`).test(h)) total += 4;
    else if (h.includes(w)) total += 3;
    else if (r.includes(w)) total += 1;
    else return 0;
  }
  return total;
}

let loaded: Promise<SearchEntry[]> | null = null;
const loadIndex = () => (loaded ??= import('../content/source/search.json').then((m) => m.default as SearchEntry[]));

export function SearchDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [q, setQ] = useState('');
  const [entries, setEntries] = useState<SearchEntry[] | null>(null);
  const [active, setActive] = useState(0);
  const input = useRef<HTMLInputElement>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const listId = useId();

  useEffect(() => {
    const d = dialog.current;
    if (!d) return;
    if (open && !d.open) {
      d.showModal();
      input.current?.focus();
      input.current?.select();
      loadIndex().then(setEntries);
    } else if (!open && d.open) d.close();
  }, [open]);

  const sectionTitle = useMemo(() => new Map(sourceIndex.chapters.flatMap((c) => c.sections.map((s) => [s.id, `${s.number} ${s.title}`] as const))), []);
  const hits = useMemo<Hit[]>(() => {
    const words = fold(q).split(/\s+/).filter(Boolean);
    if (words.length === 0) return [];
    const out: Hit[] = [];
    for (const c of sourceIndex.chapters) {
      for (const s of c.sections) {
        const blurb = PLANS.find((p) => p.id === s.id)?.blurb ?? '';
        const sc = score(words, `${s.number} ${s.title}`, `${c.title} ${blurb}`);
        if (sc) out.push({ href: `#/s/${s.id}`, kind: 'section', head: `${s.number} ${s.title}`, sub: blurb || c.title, where: c.number ? `Chapter ${c.number}` : c.title, score: sc + 2 });
      }
    }
    for (const e of entries ?? []) {
      const sc = score(words, `${e.head} ${e.title ?? ''} ${e.keys ?? ''}`, e.text);
      if (!sc) continue;
      out.push({
        href: `#/s/${e.sectionId}?mode=formal&at=${e.anchor}`,
        kind: e.kind,
        head: e.title ? `${e.head} (${e.title})` : e.head,
        sub: e.text,
        where: sectionTitle.get(e.sectionId) ?? '',
        score: sc + (e.kind === 'term' ? 1 : 0),
      });
    }
    return out.sort((a, b) => b.score - a.score).slice(0, 40);
  }, [q, entries, sectionTitle]);

  useEffect(() => setActive(0), [q]);

  const go = (h: Hit | undefined) => {
    if (!h) return;
    window.location.hash = h.href.slice(1);
    onClose();
  };

  return (
    <dialog
      ref={dialog}
      className="search-dialog"
      aria-label="Search the book"
      onClose={onClose}
      onClick={(e) => {
        if (e.target === dialog.current) onClose();
      }}
    >
      <div className="search-box">
        <input
          ref={input}
          className="search-input"
          type="search"
          placeholder="Search sections, definitions, theorems, terms…"
          value={q}
          onChange={(e) => setQ(e.target.value)}
          role="combobox"
          aria-expanded={hits.length > 0}
          aria-controls={listId}
          aria-activedescendant={hits.length ? `${listId}-${active}` : undefined}
          onKeyDown={(e) => {
            if (e.key === 'ArrowDown') {
              e.preventDefault();
              setActive((a) => Math.min(hits.length - 1, a + 1));
            } else if (e.key === 'ArrowUp') {
              e.preventDefault();
              setActive((a) => Math.max(0, a - 1));
            } else if (e.key === 'Enter') {
              e.preventDefault();
              go(hits[active]);
            }
          }}
        />
        <ul id={listId} className="search-results" role="listbox" aria-label="Results">
          {q.trim() && entries === null && <li className="search-empty">Loading the index…</li>}
          {q.trim() && entries !== null && hits.length === 0 && <li className="search-empty">Nothing found.</li>}
          {hits.map((h, i) => (
            <li
              key={`${h.href}-${h.kind}-${h.head}`}
              id={`${listId}-${i}`}
              role="option"
              aria-selected={i === active}
              className={i === active ? 'active' : ''}
              onMouseMove={() => setActive(i)}
              onClick={() => go(h)}
            >
              <div className="search-head">
                <span className={`search-kind k-${h.kind}`}>{KIND[h.kind] ?? h.kind}</span> {h.head}
              </div>
              {h.sub && <div className="search-sub">{h.sub}</div>}
              <div className="search-where">{h.where}</div>
            </li>
          ))}
        </ul>
        <div className="search-foot">
          <span>
            <kbd>↑</kbd> <kbd>↓</kbd> to move, <kbd>Enter</kbd> to open, <kbd>Esc</kbd> to close
          </span>
        </div>
      </div>
    </dialog>
  );
}
