// Data for the reference pages.

export interface TimelineEvent {
  year: number;
  title: string;
  who: string;
  text: string;
  ch?: string;
  track: 'logic' | 'lambda' | 'types' | 'systems';
}

export const timeline: TimelineEvent[] = [
  { year: 1901, title: "Russell's paradox", who: 'Bertrand Russell', text: 'The set of all sets that do not contain themselves breaks Frege’s logic.', track: 'logic', ch: 'intro' },
  { year: 1908, title: 'Ramified type theory', who: 'Russell', text: 'Types are introduced to avoid the paradoxes; later used in Principia Mathematica (1910–13).', track: 'types', ch: 'universes' },
  { year: 1928, title: 'Entscheidungsproblem', who: 'Hilbert & Ackermann', text: 'Is there an algorithm to decide the validity of formulas?', track: 'logic' },
  { year: 1932, title: 'The λ-calculus', who: 'Alonzo Church', text: 'Introduced as part of a logical system (shown inconsistent in 1935).', track: 'lambda', ch: 'lambda' },
  { year: 1934, title: 'Functionality', who: 'Haskell Curry', text: 'Types of combinators match axioms of implicational logic.', track: 'types', ch: 'curry-howard' },
  { year: 1935, title: 'Natural deduction', who: 'Gerhard Gentzen', text: 'Introduction and elimination rules for each connective.', track: 'logic', ch: 'curry-howard' },
  { year: 1936, title: 'Church–Rosser; undecidability', who: 'Church, Rosser, Turing', text: 'Confluence of β-reduction; the halting problem is undecidable.', track: 'lambda', ch: 'lambda' },
  { year: 1940, title: 'Simple theory of types', who: 'Church', text: 'The simply typed λ-calculus as a higher-order logic.', track: 'types', ch: 'stlc' },
  { year: 1958, title: 'System T', who: 'Kurt Gödel', text: 'Primitive recursion at higher types (published 1958).', track: 'types', ch: 'recursion' },
  { year: 1965, title: 'Proof normalisation', who: 'Dag Prawitz', text: 'Natural deduction proofs normalise.', track: 'logic', ch: 'curry-howard' },
  { year: 1967, title: 'Automath', who: 'N. G. de Bruijn', text: 'The first proof checker for mathematics, based on dependent types.', track: 'systems', ch: 'dependent' },
  { year: 1967, title: 'Strong normalisation of λ→', who: 'William Tait', text: 'The reducibility method.', track: 'types', ch: 'stlc' },
  { year: 1969, title: 'Formulae-as-types', who: 'William Howard', text: 'The Curry–Howard correspondence for natural deduction (published 1980).', track: 'types', ch: 'curry-howard' },
  { year: 1969, title: 'Models of the λ-calculus', who: 'Dana Scott', text: 'D ≅ D → D: the first semantics of untyped λ.', track: 'lambda', ch: 'positivity' },
  { year: 1971, title: 'Type : Type', who: 'Per Martin-Löf', text: 'The first intuitionistic type theory, soon shown inconsistent.', track: 'types', ch: 'universes' },
  { year: 1972, title: 'System F & Girard’s paradox', who: 'Jean-Yves Girard', text: 'Polymorphism, reducibility candidates, and the inconsistency of Type : Type.', track: 'types', ch: 'system-f' },
  { year: 1972, title: 'Nameless dummies', who: 'de Bruijn', text: 'De Bruijn indices.', track: 'lambda', ch: 'binders' },
  { year: 1974, title: 'Polymorphic λ-calculus', who: 'John Reynolds', text: 'System F rediscovered for programming languages.', track: 'types', ch: 'system-f' },
  { year: 1978, title: 'Type inference for ML', who: 'Robin Milner', text: 'Hindley–Milner type inference.', track: 'systems', ch: 'stlc' },
  { year: 1979, title: 'W-types', who: 'Martin-Löf', text: 'A general inductive type; Martin-Löf type theory matures (1984 book).', track: 'types', ch: 'inductive' },
  { year: 1985, title: 'Calculus of Constructions', who: 'Coquand & Huet', text: 'All four dependencies in one calculus.', track: 'types', ch: 'coc' },
  { year: 1987, title: 'LF', who: 'Harper, Honsell & Plotkin', text: 'A framework for defining logics.', track: 'types', ch: 'dependent' },
  { year: 1988, title: 'Inductive types in CoC', who: 'Coquand & Paulin-Mohring', text: 'The Calculus of Inductive Constructions.', track: 'types', ch: 'inductive' },
  { year: 1989, title: 'Coq', who: 'INRIA', text: 'The first release of the Coq proof assistant.', track: 'systems', ch: 'lean' },
  { year: 1990, title: 'ECC', who: 'Zhaohui Luo', text: 'Impredicative Prop under a predicative hierarchy.', track: 'types', ch: 'universes' },
  { year: 1991, title: 'The λ-cube', who: 'Henk Barendregt', text: 'Eight calculi, and Pure Type Systems.', track: 'types', ch: 'cube' },
  { year: 1994, title: 'Inductive families; normalisation of CIC', who: 'Dybjer; Werner', text: 'The schema for families; strong normalisation for CIC.', track: 'types', ch: 'families' },
  { year: 1995, title: "Hurkens' paradox", who: 'Antonius Hurkens', text: 'A short version of Girard’s paradox.', track: 'types', ch: 'universes' },
  { year: 2005, title: 'Four Colour Theorem', who: 'Georges Gonthier', text: 'Formally verified in Coq.', track: 'systems', ch: 'intro' },
  { year: 2006, title: 'Eliminating dependent pattern matching', who: 'Goguen, McBride & McKinna', text: 'Compiling pattern matching to eliminators.', track: 'types', ch: 'families' },
  { year: 2009, title: 'Univalence', who: 'Vladimir Voevodsky', text: 'Types as spaces, equality as paths.', track: 'types', ch: 'beyond' },
  { year: 2013, title: 'Lean', who: 'Leonardo de Moura', text: 'Lean is started at Microsoft Research.', track: 'systems', ch: 'lean' },
  { year: 2015, title: 'Cubical type theory', who: 'Cohen, Coquand, Huber & Mörtberg', text: 'Univalence that computes.', track: 'types', ch: 'beyond' },
  { year: 2021, title: 'Lean 4', who: 'de Moura & Ullrich', text: 'Lean reimplemented in Lean.', track: 'systems', ch: 'lean' },
  { year: 2022, title: 'Liquid Tensor Experiment', who: 'Lean community', text: 'A cutting-edge theorem of Clausen–Scholze formalised in Lean.', track: 'systems', ch: 'lean' },
  { year: 2025, title: 'Coq becomes Rocq', who: '', text: 'The Coq proof assistant is renamed the Rocq Prover.', track: 'systems', ch: 'lean' },
];

export const glossary: { term: string; def: string; ch: string }[] = [
  { term: 'α-equivalence', def: 'Equality of terms up to renaming of bound variables.', ch: 'lambda' },
  { term: 'β-reduction', def: 'The computation rule (λx. t) a ⟶ t[a/x].', ch: 'lambda' },
  { term: 'δ-reduction', def: 'Unfolding a definition by its body.', ch: 'cic' },
  { term: 'ζ-reduction', def: 'Substituting the value of a let-bound variable.', ch: 'cic' },
  { term: 'η-conversion', def: 'λx. f x ≡ f (and, for structures, p ≡ ⟨p.1, p.2⟩).', ch: 'cic' },
  { term: 'ι-reduction', def: 'A recursor applied to a constructor computes by the corresponding minor premise.', ch: 'inductive' },
  { term: 'Accessibility', def: 'Acc r x: every descending r-chain from x is finite; the basis of well-founded recursion.', ch: 'beyond-structural' },
  { term: 'Axiom', def: 'A constant with a type but no definition; it blocks computation.', ch: 'lean' },
  { term: 'Bidirectional elaboration', def: 'Type checking where expected types flow into terms and inferred types flow out.', ch: 'cic' },
  { term: 'Canonicity', def: 'Every closed term of an inductive type reduces to a constructor application.', ch: 'metatheory' },
  { term: 'casesOn', def: 'The non-recursive eliminator derived from a recursor: case analysis without induction hypotheses.', ch: 'recursion' },
  { term: 'Confluence', def: 'If a term reduces to two terms, those reduce to a common term (Church–Rosser).', ch: 'lambda' },
  { term: 'Constructor', def: 'One of the ways to build an element of an inductive type.', ch: 'inductive' },
  { term: 'Context', def: 'A list of typing assumptions x : A about free variables.', ch: 'stlc' },
  { term: 'Conversion', def: 'The typing rule that lets a term have any type definitionally equal to its type.', ch: 'fomega' },
  { term: 'Curry–Howard correspondence', def: 'Propositions are types and proofs are programs.', ch: 'curry-howard' },
  { term: 'de Bruijn criterion', def: 'All proofs are checked by a small trusted kernel.', ch: 'intro' },
  { term: 'de Bruijn index', def: 'A bound variable written as the number of binders between it and its binder.', ch: 'binders' },
  { term: 'Definitional equality', def: 'The equality the kernel decides by computation (≡), as opposed to the proposition a = b.', ch: 'families' },
  { term: 'Derivation', def: 'A tree of rule applications establishing a judgement.', ch: 'stlc' },
  { term: 'Elaborator', def: 'The untrusted component that turns surface syntax into kernel terms, filling in implicit information.', ch: 'cic' },
  { term: 'Environment', def: 'The global list of declarations (Σ): axioms, definitions, inductive types.', ch: 'cic' },
  { term: 'Impredicativity', def: 'Quantification over a universe that includes the type being defined, as in ∀ p : Prop, p.', ch: 'system-f' },
  { term: 'Index', def: 'An argument of an inductive family that varies between constructors (as opposed to a parameter).', ch: 'families' },
  { term: 'Inductive family', def: 'An inductive type indexed by values, such as Vec α n.', ch: 'families' },
  { term: 'Judgement', def: 'An assertion like Γ ⊢ t : A, derivable from the rules.', ch: 'stlc' },
  { term: 'Kernel', def: 'The small, trusted type checker that validates every declaration.', ch: 'intro' },
  { term: 'Kind', def: 'The type of a type or type operator, such as * → *.', ch: 'fomega' },
  { term: 'Large elimination', def: 'Eliminating an inductive type into a universe (computing types or propositions by recursion).', ch: 'inductive' },
  { term: 'Locally nameless', def: 'Bound variables as de Bruijn indices, free variables as unique names.', ch: 'binders' },
  { term: 'Major premise', def: 'The element being eliminated by a recursor.', ch: 'inductive' },
  { term: 'Metavariable', def: 'A hole in a term, to be solved by the elaborator (by unification).', ch: 'stlc' },
  { term: 'Minor premise', def: 'One case of a recursor, for one constructor.', ch: 'inductive' },
  { term: 'Motive', def: 'The type family a recursor produces elements of.', ch: 'inductive' },
  { term: 'Normal form', def: 'A term with no redexes.', ch: 'lambda' },
  { term: 'Parameter', def: 'An argument of an inductive type that is uniform across all constructors.', ch: 'families' },
  { term: 'Π-type', def: 'The type (x : A) → B of dependent functions.', ch: 'dependent' },
  { term: 'Proof irrelevance', def: 'Any two proofs of the same proposition are (definitionally) equal.', ch: 'prop' },
  { term: 'Pure Type System', def: 'A family of typed λ-calculi given by sorts, axioms and product rules.', ch: 'cube' },
  { term: 'Quotient', def: 'The type Quot r of equivalence classes of a relation r.', ch: 'lean' },
  { term: 'Recursor', def: 'The eliminator generated for an inductive type; recursion and induction principle in one.', ch: 'inductive' },
  { term: 'Redex', def: 'A reducible expression, such as (λx. t) a.', ch: 'lambda' },
  { term: 'Sort', def: 'A type of types: Prop, Type, Type 1, … (Sort u in Lean).', ch: 'universes' },
  { term: 'Strict positivity', def: 'The restriction that an inductive type occurs in its constructors only as the final result of argument types.', ch: 'positivity' },
  { term: 'Strong normalisation', def: 'Every reduction sequence from a well-typed term terminates.', ch: 'stlc' },
  { term: 'Structural recursion', def: 'Recursion where each call is on a constructor field of the argument.', ch: 'recursion' },
  { term: 'Subject reduction', def: 'Reduction preserves types.', ch: 'stlc' },
  { term: 'Subsingleton elimination', def: 'The rule deciding which propositions may be eliminated into Type.', ch: 'prop' },
  { term: 'Universe', def: 'A type whose elements are types.', ch: 'universes' },
  { term: 'Universe polymorphism', def: 'Definitions parameterised by universe levels.', ch: 'universes' },
  { term: 'Weak head normal form', def: 'A term whose head is not a redex (a λ, a Π, a sort, or a stuck application).', ch: 'cic' },
];

export const bibliography: { ch: string; items: string[] }[] = [
  { ch: 'intro', items: ['N. G. de Bruijn, *A survey of the project Automath* (1980).', 'G. Gonthier, *Formal proof — the four-color theorem*, Notices of the AMS (2008).', 'J. Avigad, *The mechanization of mathematics*, Notices of the AMS (2018).'] },
  { ch: 'lambda', items: ['H. Barendregt, *The Lambda Calculus: Its Syntax and Semantics* (1984).', 'J. R. Hindley and J. P. Seldin, *Lambda-Calculus and Combinators: An Introduction* (2008).', 'F. Cardone and J. R. Hindley, *History of Lambda-calculus and Combinatory Logic* (2006).'] },
  { ch: 'binders', items: ['N. G. de Bruijn, *Lambda calculus notation with nameless dummies* (1972).', 'A. Charguéraud, *The Locally Nameless Representation*, JAR (2012).'] },
  { ch: 'stlc', items: ['A. Church, *A formulation of the simple theory of types* (1940).', 'B. Pierce, *Types and Programming Languages* (2002), chapters 9–12.', 'W. W. Tait, *Intensional interpretations of functionals of finite type I* (1967).'] },
  { ch: 'curry-howard', items: ['W. A. Howard, *The formulae-as-types notion of construction* (1980).', 'P. Wadler, *Propositions as Types*, CACM (2015).', 'M. H. Sørensen and P. Urzyczyn, *Lectures on the Curry–Howard Isomorphism* (2006).'] },
  { ch: 'system-f', items: ['J.-Y. Girard, Y. Lafont and P. Taylor, *Proofs and Types* (1989).', 'J. C. Reynolds, *Towards a theory of type structure* (1974).', 'P. Wadler, *Theorems for free!* (1989).'] },
  { ch: 'cube', items: ['H. Barendregt, *Introduction to generalized type systems*, JFP (1991).', 'H. Barendregt, *Lambda calculi with types*, Handbook of Logic in Computer Science (1992).'] },
  { ch: 'coc', items: ['T. Coquand and G. Huet, *The Calculus of Constructions*, Information and Computation (1988).'] },
  { ch: 'universes', items: ['A. J. C. Hurkens, *A simplification of Girard’s paradox* (1995).', 'Z. Luo, *An Extended Calculus of Constructions*, PhD thesis (1990).', 'T. Coquand, *An analysis of Girard’s paradox* (1986).'] },
  { ch: 'inductive', items: ['T. Coquand and C. Paulin-Mohring, *Inductively defined types* (1990).', 'P. Martin-Löf, *Intuitionistic Type Theory* (1984).', 'The Rocq Reference Manual, chapter on the Calculus of Inductive Constructions.'] },
  { ch: 'families', items: ['P. Dybjer, *Inductive families*, Formal Aspects of Computing (1994).', 'H. Goguen, C. McBride and J. McKinna, *Eliminating dependent pattern matching* (2006).', 'J. Cockx, *Dependent pattern matching and proof-relevant unification*, PhD thesis (2017).'] },
  { ch: 'prop', items: ['G. Gilbert, J. Cockx, M. Sozeau and N. Tabareau, *Definitional proof-irrelevance without K* (2019).'] },
  { ch: 'recursion', items: ['E. Giménez, *Codifying guarded definitions with recursive schemes* (1994).', 'T. Coquand, *Pattern matching with dependent types* (1992).'] },
  { ch: 'metatheory', items: ['B. Werner, *Sets in types, types in sets* (1997).', 'M. Carneiro, *The Type Theory of Lean*, MSc thesis (2019).', 'A. Abel and T. Coquand, *Failure of normalization in impredicative type theory with proof-irrelevant propositional equality* (2020).', 'M. Sozeau et al., *The MetaCoq Project*, JAR (2020).'] },
  { ch: 'lean', items: ['J. Avigad, L. de Moura, S. Kong and S. Ullrich, *Theorem Proving in Lean 4*.', 'L. de Moura and S. Ullrich, *The Lean 4 theorem prover and programming language* (2021).'] },
  { ch: 'beyond', items: ['The Univalent Foundations Program, *Homotopy Type Theory* (2013).', 'C. Cohen, T. Coquand, S. Huber and A. Mörtberg, *Cubical type theory* (2015).', 'T. Altenkirch, C. McBride and W. Swierstra, *Observational equality, now!* (2007).'] },
];
