import { defineComponents } from './registry';

/** Logic-level inputs and outputs for the digital engines. */
defineComponents([
  {
    type: 'toggle',
    name: 'Logic switch',
    category: 'io',
    description: 'A switch that outputs logic 0 or 1. Click it to flip.',
    pins: [{ name: 'Y', x: 3, y: 0, dir: 'out' }],
    bounds: { x0: -1, y0: -1, x1: 3, y1: 1 },
    params: [{ key: 'on', label: 'On', kind: 'boolean', default: false }],
    engines: ['digital', 'switch', 'analog'],
  },
  {
    type: 'button',
    name: 'Logic pushbutton',
    category: 'io',
    description: 'Outputs 1 while held down, 0 otherwise.',
    pins: [{ name: 'Y', x: 3, y: 0, dir: 'out' }],
    bounds: { x0: -1, y0: -1, x1: 3, y1: 1 },
    params: [{ key: 'pressed', label: 'Pressed', kind: 'boolean', default: false }],
    engines: ['digital', 'switch', 'analog'],
  },
  {
    type: 'clock',
    name: 'Clock',
    category: 'io',
    description: 'A square wave between 0 and 1.',
    pins: [{ name: 'Y', x: 3, y: 0, dir: 'out' }],
    bounds: { x0: -2, y0: -1, x1: 3, y1: 1 },
    params: [
      { key: 'frequency', label: 'Frequency', kind: 'number', default: 1, unit: 'Hz', min: 0.01, max: 1e9, log: true },
      { key: 'duty', label: 'Duty cycle', kind: 'number', default: 0.5, min: 0.01, max: 0.99, step: 0.01 },
    ],
    engines: ['digital', 'switch', 'analog'],
  },
  {
    type: 'const',
    name: 'Constant',
    category: 'io',
    description: 'A fixed logic 0 or 1.',
    pins: [{ name: 'Y', x: 2, y: 0, dir: 'out' }],
    bounds: { x0: -1, y0: -1, x1: 2, y1: 1 },
    params: [{ key: 'value', label: 'Value', kind: 'number', default: 1, min: 0, max: 1, step: 1 }],
    engines: ['digital', 'switch', 'analog'],
  },
  {
    type: 'indicator',
    name: 'Logic LED',
    category: 'io',
    description: 'Lights when its input is 1 (an LED with its resistor and driver, drawn as one).',
    pins: [{ name: 'A', x: 0, y: 0, dir: 'in' }],
    bounds: { x0: 0, y0: -1, x1: 3, y1: 1 },
    params: [{ key: 'color', label: 'Colour', kind: 'enum', default: 'red', options: ['red', 'amber', 'green', 'blue', 'white'] }],
    engines: ['digital', 'switch', 'analog'],
  },
  {
    type: 'probe',
    name: 'Logic probe',
    category: 'io',
    description: 'Shows the logic value of a net: 0, 1, X (unknown) or Z (floating).',
    pins: [{ name: 'A', x: 0, y: 0, dir: 'in' }],
    bounds: { x0: 0, y0: -1, x1: 3, y1: 1 },
    params: [{ key: 'name', label: 'Name', kind: 'string', default: '' }],
    engines: ['digital', 'switch', 'analog'],
  },
  {
    type: 'seven-seg',
    name: '7-segment display',
    category: 'io',
    description: 'Seven segments a–g and a decimal point, each lit by a 1.',
    pins: ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'dp'].map((name, i) => ({ name, x: 0, y: 2 * i, dir: 'in' as const })),
    bounds: { x0: 0, y0: -1, x1: 8, y1: 15 },
    engines: ['digital', 'switch'],
  },
  {
    type: 'hex-display',
    name: 'Hex display',
    category: 'io',
    description: 'Shows the 4-bit input (D3 is the most significant bit) as a hexadecimal digit.',
    pins: ['D0', 'D1', 'D2', 'D3'].map((name, i) => ({ name, x: 0, y: 2 * i, dir: 'in' as const })),
    bounds: { x0: 0, y0: -1, x1: 6, y1: 7 },
    engines: ['digital', 'switch'],
  },
]);
