/**
 * The final-state shower: a pT-ordered cascade with the Sudakov veto algorithm, run for each colour-connected system
 * in its own centre-of-mass frame, followed by an exact four-momentum rescaling.
 */
import type { TruthEvent, TruthParticle } from '../event/index.ts';
import { boost, type P4 } from '../kinematics/index.ts';
import type { Rng } from '../random/index.ts';
import { particle } from '../particles/index.ts';
import { buildChains, ensureColour, maxColour, outgoingPartons, type Chain } from '../hadronise/colour.ts';
import { rescaleToTarget } from './rescale.ts';
import { alphaSShower, alphaSOver, B0_NF5, CA, CF, LAMBDA2, overestimateFactor, TR } from './splitting.ts';

export interface ShowerOptions {
  /** Final-state radiation. Default true. */
  fsr?: boolean;
  /** Initial-state radiation (only for events with coloured incoming partons; see README). Default true. */
  isr?: boolean;
  /**
   * The hard scale Q in GeV: the first emission has pT ≤ Q/2 (and never more than half the radiator's energy).
   * Default: for each colour-connected system its invariant mass; for ISR the invariant mass of the hard system.
   */
  startScale?: number;
  /** Lower cut on the emission pT in GeV (the shower stops below it). Default 1, minimum 0.5. */
  cutoff?: number;
  /** A fixed αs instead of the running coupling (toy studies, tests). */
  alphaSFixed?: number;
  /** A fixed number of flavours for g → qq̄ instead of the quark-mass thresholds (the course text uses nf = 5). */
  nf?: number;
  /** Switch off angular ordering (colour coherence) of the final-state cascade. Default false (ordering on). */
  noAngularOrdering?: boolean;
}

export interface EmissionConfig {
  alphaSFixed?: number;
  nf?: number;
  /** Switch the angular-ordering (colour coherence) veto off in the cascade. */
  noAngularOrdering?: boolean;
}

export type BranchKind = 'q->qg' | 'g->gg' | 'g->qq';
export interface Emission {
  /** pT² of the emission. */
  t: number;
  /** Energy fraction of the first daughter. */
  z: number;
  kind: BranchKind;
  /** Flavour (PDG ID > 0) of the quark in g → qq̄, else 0. */
  flavour: number;
}

const FLAVOURS = [2, 1, 3, 4, 5];
const FLAVOUR_MASS: Record<number, number> = { 1: 0, 2: 0, 3: 0, 4: 1.27, 5: 4.18 };

/**
 * The Sudakov veto algorithm for one radiating parton: the next branching of a parton with energy E, starting the
 * evolution at pT² = `tmax` and stopping below `tmin`; null if nothing is emitted above the cutoff.
 *
 * The true emission density is (αs(t)/2π) P(z) dz dt/t on the z range [pT/E, 1 − pT/E]. It is overestimated by
 * K·αs_o(t) times a z-independent integral of a simple majorant of P over the widest range (z ∈ [ε, 1 − ε], ε = √tmin/E);
 * trial scales are generated by inverting the overestimated Sudakov analytically, and each trial is accepted with the
 * ratio true/overestimate (coupling, splitting function, z range, flavour thresholds), which makes the result exact.
 * `thetaMax` (default none) adds the angular-ordering veto: the opening angle of the new pair, pT/(z(1−z)E), must be below it.
 */
export function nextEmission(isGluon: boolean, E: number, tmax: number, tmin: number, rng: Rng, cfg: EmissionConfig = {}, thetaMax = Infinity): Emission | null {
  const eps0 = Math.sqrt(tmin) / E;
  if (!(eps0 < 0.5) || !(tmax > tmin)) return null;
  const L = Math.log((1 - eps0) / eps0);
  const nfMax = cfg.nf ?? 5;
  const Rgg = isGluon ? CA * 2 * L : 0; // ∫ CA/(z(1−z)) over the widest range
  const Rqg = isGluon ? 0 : 2 * CF * L; // ∫ 2CF/(1−z)
  const Rgq = isGluon ? nfMax * TR * (1 - 2 * eps0) : 0;
  const R = Rgg + Rqg + Rgq;
  const fixed = cfg.alphaSFixed;
  const K = fixed === undefined ? overestimateFactor() : 1;
  let t = tmax;
  for (let trial = 0; trial < 100000; trial++) {
    const u = rng();
    if (fixed !== undefined) t *= Math.pow(u, (2 * Math.PI) / (R * fixed));
    else t = LAMBDA2 * Math.exp(Math.log(t / LAMBDA2) * Math.pow(u, (2 * Math.PI * B0_NF5) / (R * K)));
    if (!(t > tmin)) return null;
    // coupling
    if (fixed === undefined && rng() * K * alphaSOver(t) > alphaSShower(t)) continue;
    const zmin = Math.sqrt(t) / E;
    if (isGluon) {
      const pick = rng() * R;
      if (pick < Rgg) {
        const v = L * (2 * rng() - 1);
        const z = 1 / (1 + Math.exp(-v));
        if (z < zmin || z > 1 - zmin) continue;
        if (Math.sqrt(t) > thetaMax * z * (1 - z) * E) continue; // angular ordering
        const f = 1 - z * (1 - z);
        if (rng() > f * f) continue;
        return { t, z, kind: 'g->gg', flavour: 0 };
      }
      const z = eps0 + (1 - 2 * eps0) * rng();
      if (z < zmin || z > 1 - zmin) continue;
      if (Math.sqrt(t) > thetaMax * z * (1 - z) * E) continue; // angular ordering
      if (rng() > z * z + (1 - z) * (1 - z)) continue;
      let fl = 0;
      if (cfg.nf !== undefined) {
        fl = FLAVOURS[Math.floor(rng() * Math.min(cfg.nf, 5))] ?? 2;
      } else {
        const pT = Math.sqrt(t);
        const act: number[] = [];
        for (const f of FLAVOURS) if (FLAVOUR_MASS[f]! < pT) act.push(f);
        if (rng() * 5 >= act.length) continue; // nf(pT)/5
        fl = act[Math.floor(rng() * act.length)]!;
      }
      return { t, z, kind: 'g->qq', flavour: fl };
    }
    const w = eps0 * Math.exp(L * rng());
    const z = 1 - w;
    if (z < zmin || w < zmin) continue;
    if (Math.sqrt(t) > thetaMax * z * w * E) continue; // angular ordering
    if (rng() * 2 > 1 + z * z) continue;
    return { t, z, kind: 'q->qg', flavour: 0 };
  }
  return null;
}

// ── The cascade ───────────────────────────────────────────────────────────────────────────────────────────────

interface Node {
  pdg: number;
  E: number;
  px: number;
  py: number;
  pz: number;
  col: number;
  acol: number;
  parent: number;
  d1: number;
  d2: number;
  /** Evolution scale (pT²) at which this node was created: its own emissions are ordered below it. */
  t: number;
  /** Index of the truth particle if this node is a root. */
  truth: number;
  /** Opening angle of the branching that created this node (angular-ordering bound for its own emissions); Infinity for a root. */
  theta: number;
}

function runCascade(nodes: Node[], tmin: number, rng: Rng, cfg: EmissionConfig, nextColour: { n: number }): void {
  for (let i = 0; i < nodes.length; i++) {
    const nd = nodes[i]!;
    const E = nd.E;
    const tm = Math.min(nd.t, (E * E) / 4);
    const isG = nd.pdg === 21;
    const em = nextEmission(isG, E, tm, tmin, rng, cfg, cfg.noAngularOrdering ? Infinity : nd.theta);
    if (!em) continue;
    const p = Math.sqrt(nd.px * nd.px + nd.py * nd.py + nd.pz * nd.pz);
    if (!(p > 0)) continue;
    const nx = nd.px / p, ny = nd.py / p, nz = nd.pz / p;
    // orthonormal basis (e1, e2) ⟂ n
    let e1x: number, e1y: number, e1z: number;
    if (Math.abs(nz) < 0.9) {
      const s = Math.hypot(nx, ny);
      e1x = -ny / s; e1y = nx / s; e1z = 0;
    } else {
      const s = Math.hypot(nx, nz);
      e1x = nz / s; e1y = 0; e1z = -nx / s;
    }
    const e2x = ny * e1z - nz * e1y, e2y = nz * e1x - nx * e1z, e2z = nx * e1y - ny * e1x;
    const phi = 2 * Math.PI * rng();
    const k = Math.sqrt(em.t);
    const kx = k * (Math.cos(phi) * e1x + Math.sin(phi) * e2x);
    const ky = k * (Math.cos(phi) * e1y + Math.sin(phi) * e2y);
    const kz = k * (Math.cos(phi) * e1z + Math.sin(phi) * e2z);
    const E1 = em.z * E, E2 = (1 - em.z) * E;
    const pl1 = Math.sqrt(Math.max(0, E1 * E1 - em.t)), pl2 = Math.sqrt(Math.max(0, E2 * E2 - em.t));
    let pdg1: number, pdg2: number;
    let c1 = 0, a1 = 0, c2 = 0, a2 = 0;
    if (em.kind === 'q->qg') {
      pdg1 = nd.pdg;
      pdg2 = 21;
      const n = nextColour.n++;
      if (nd.pdg > 0) {
        c1 = n; a1 = 0; c2 = nd.col; a2 = n;
      } else {
        c1 = 0; a1 = n; c2 = n; a2 = nd.acol;
      }
    } else if (em.kind === 'g->gg') {
      pdg1 = 21;
      pdg2 = 21;
      const n = nextColour.n++;
      if (rng() < 0.5) {
        c1 = nd.col; a1 = n; c2 = n; a2 = nd.acol;
      } else {
        c1 = n; a1 = nd.acol; c2 = nd.col; a2 = n;
      }
    } else {
      pdg1 = em.flavour;
      pdg2 = -em.flavour;
      c1 = nd.col; a1 = 0; c2 = 0; a2 = nd.acol;
    }
    const i1 = nodes.length;
    const b1x = pl1 * nx + kx, b1y = pl1 * ny + ky, b1z = pl1 * nz + kz;
    const b2x = pl2 * nx - kx, b2y = pl2 * ny - ky, b2z = pl2 * nz - kz;
    const cosT = (b1x * b2x + b1y * b2y + b1z * b2z) / (E1 * E2);
    const theta = Math.acos(Math.max(-1, Math.min(1, cosT)));
    nodes.push({ pdg: pdg1, E: E1, px: b1x, py: b1y, pz: b1z, col: c1, acol: a1, parent: i, d1: -1, d2: -1, t: em.t, truth: -1, theta });
    nodes.push({ pdg: pdg2, E: E2, px: b2x, py: b2y, pz: b2z, col: c2, acol: a2, parent: i, d1: -1, d2: -1, t: em.t, truth: -1, theta });
    nd.d1 = i1;
    nd.d2 = i1 + 1;
    if (nodes.length > 20000) break; // cannot happen for physical settings; a hard stop against runaway cascades
  }
}

/** Quark masses for the rescaling (u, d, s are taken massless in the shower). */
function leafMass(pdg: number): number {
  const a = Math.abs(pdg);
  return a === 4 || a === 5 ? particle(a).mass : 0;
}

/**
 * Shower one colour-connected system (a list of truth indices whose momenta add up to the system's momentum).
 * Returns true if anything was emitted.
 */
function showerSystem(ev: TruthEvent, idx: number[], rng: Rng, tmin: number, startScale: number | undefined, cfg: EmissionConfig, nextColour: { n: number }): boolean {
  const roots = idx.map((i) => ev.particles[i]!);
  let E = 0, px = 0, py = 0, pz = 0;
  for (const r of roots) {
    E += r.p.E;
    px += r.p.px;
    py += r.p.py;
    pz += r.p.pz;
  }
  const W2 = (E - Math.hypot(px, py, pz)) * (E + Math.hypot(px, py, pz));
  if (!(W2 > 0)) return false;
  const W = Math.sqrt(W2);
  const Q = startScale ?? W;
  const t0 = (Q * Q) / 4;
  if (!(t0 > tmin)) return false;
  const bx = -px / E, by = -py / E, bz = -pz / E;
  const nodes: Node[] = [];
  for (let k = 0; k < roots.length; k++) {
    const r = roots[k]!;
    const c = boost(r.p, bx, by, bz);
    nodes.push({ pdg: r.pdg, E: c.E, px: c.px, py: c.py, pz: c.pz, col: r.colour?.[0] ?? 0, acol: r.colour?.[1] ?? 0, parent: -1, d1: -1, d2: -1, t: t0, truth: idx[k]!, theta: Infinity });
  }
  const nRoots = nodes.length;
  runCascade(nodes, tmin, rng, cfg, nextColour);
  if (nodes.length === nRoots) return false;
  // Leaves in the lab frame, then the exact rescaling to the system's original four-momentum.
  const leaves: number[] = [];
  for (let i = 0; i < nodes.length; i++) if (nodes[i]!.d1 < 0) leaves.push(i);
  const pv: P4[] = [];
  const ms: number[] = [];
  for (const li of leaves) {
    const nd = nodes[li]!;
    pv.push(boost({ E: nd.E, px: nd.px, py: nd.py, pz: nd.pz }, -bx, -by, -bz));
    ms.push(leafMass(nd.pdg));
  }
  const target: P4 = { E, px, py, pz };
  if (!rescaleToTarget(pv, ms, target)) return false;
  // Node momenta: leaves from the rescaled values, internal nodes as the sum of their daughters.
  const mom = new Array<P4>(nodes.length);
  leaves.forEach((li, k) => (mom[li] = pv[k]!));
  for (let i = nodes.length - 1; i >= 0; i--) {
    const nd = nodes[i]!;
    if (nd.d1 >= 0) {
      const a = mom[nd.d1]!, b = mom[nd.d2]!;
      mom[i] = { E: a.E + b.E, px: a.px + b.px, py: a.py + b.py, pz: a.pz + b.pz };
    }
  }
  // Write into the event.
  const ids = new Array<number>(nodes.length).fill(-1);
  for (let k = 0; k < nRoots; k++) ids[k] = nodes[k]!.truth;
  for (let i = 0; i < nodes.length; i++) {
    const nd = nodes[i]!;
    const root = ev.particles[nodes[rootOf(nodes, i)]!.truth]!;
    if (i >= nRoots) {
      const tp: TruthParticle = {
        id: ev.particles.length,
        pdg: nd.pdg,
        p: mom[i]!,
        vertex: [root.vertex[0], root.vertex[1], root.vertex[2]],
        status: nd.d1 >= 0 ? 'intermediate' : 'final',
        mothers: [ids[nd.parent]!],
        daughters: [],
        colour: [nd.col, nd.acol],
      };
      if (root.collision !== undefined) tp.collision = root.collision;
      ev.particles.push(tp);
      ids[i] = tp.id;
      ev.particles[ids[nd.parent]!]!.daughters.push(tp.id);
    } else {
      const tp = ev.particles[ids[i]!]!;
      tp.p = mom[i]!;
      if (nd.d1 >= 0) tp.status = 'intermediate';
    }
  }
  return true;
}

function rootOf(nodes: Node[], i: number): number {
  let k = i;
  while (nodes[k]!.parent >= 0) k = nodes[k]!.parent;
  return k;
}

/** Colour-connected systems of the outgoing partons: each closed chain and ring alone; all open chains together. */
function systems(chains: Chain[]): number[][] {
  const out: number[][] = [];
  const open: number[] = [];
  for (const c of chains) {
    if (c.ring || (!c.startOpen && !c.endOpen)) out.push(c.idx);
    else open.push(...c.idx);
  }
  if (open.length > 0) out.push(open);
  return out;
}

/** Run the final-state shower on all outgoing coloured partons of the event. */
export function showerFsr(ev: TruthEvent, rng: Rng, opts: ShowerOptions = {}): void {
  const out = outgoingPartons(ev);
  if (out.length === 0) return;
  ensureColour(ev, out);
  const chains = buildChains(ev, out);
  const nextColour = { n: maxColour(ev) + 1 };
  const tmin = Math.max(opts.cutoff ?? 1, 0.5) ** 2;
  const cfg: EmissionConfig = {};
  if (opts.alphaSFixed !== undefined) cfg.alphaSFixed = opts.alphaSFixed;
  if (opts.nf !== undefined) cfg.nf = opts.nf;
  if (opts.noAngularOrdering) cfg.noAngularOrdering = true;
  for (const sys of systems(chains)) showerSystem(ev, sys, rng, tmin, opts.startScale, cfg, nextColour);
}
